apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  order: fifo

resources:
- base

configMapGenerator:
- name: replacement-config
  options:
    disableNameSuffixHash: true
    labels:
      generated-by-kustomize: "true"
  literals:
    - imagePullPolicy=Always

# NOTE: Replacements happen AFTER patches
replacements:
- source:
    kind: ConfigMap
    name: replacement-config
    fieldPath: data.imagePullPolicy
  targets:
  - select:
      kind: Deployment
      name: kubeai
    options:
      create: true
    fieldPaths:
    - spec.template.spec.containers.*.imagePullPolicy

images:
- name: substratusai/kubeai
  newTag: main