platform_checks:
  - name: Node Health
    module: CheckNodes
  - name: Check Google Group RBAC
    module: CheckGoogleGroupRBAC
  - name: Robin Cluster Health
    module: CheckRobinCluster
  - name: Root Sync Check
    module: CheckRootSyncs
  - name: VMRuntime Check
    module: CheckVMRuntime
# Workload Checks
workload_checks:
  - name: VM Workloads Health
    module: CheckVirtualMachines
    parameters:
      namespace: vm-workloads
      count: 4
  - name: VM Data Volume Health
    module: CheckDataVolumes
    parameters:
      namespace: vm-workloads
      count: 4
