apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Main namespace
namespace: gdc-cluster-health

resources:
  - ../../base

configMapGenerator:
  - name: health-check-config
    options:
      disableNameSuffixHash: true
      labels:
        generated-by-kustomize: "true"
    files:
      - config.yaml
