apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-health-validator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-health-validator
rules:
  - apiGroups:
      - validator.gdc.gke.io
    resources:
      - healthchecks
      - healthchecks/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-health-validator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-health-validator
subjects:
  - kind: ServiceAccount
    name: cluster-health-validator
    namespace: default
