apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: healthchecks.validator.gdc.gke.io
spec:
  conversion:
    strategy: None
  group: validator.gdc.gke.io
  names:
    kind: HealthCheck
    listKind: HealthCheckList
    plural: healthchecks
    singular: healthcheck
  scope: Cluster
  versions:
  - name: v1
    additionalPrinterColumns:
    - name: platform_checks
      jsonPath: ".status.conditions[?(@.type=='PlatformHealthy')].reason"
      type: string
    - name: workload_checks
      jsonPath: ".status.conditions[?(@.type=='WorkloadsHealthy')].reason"
      type: string
    schema:
      openAPIV3Schema:
        type: object
        description: Healthcheck is the Schema for the healthchecks API
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            description: HealthcheckSpec defines the desired state of Healthcheck
            properties:
              enabled:
                type: boolean
                description: Healthchecks are enabled. Notused currently
          status:
            type: object
            description: HealthcheckStatus defines the observed state of Healthcheck
            properties:
              conditions:
                type: array                    
                description: conditions represents the latest available observations
                x-kubernetes-list-map-keys: ["type"]
                x-kubernetes-list-type: "map"
                items:
                  type: object
                  properties:
                    lastTransitionTime:
                      type: string
                      description: Last time the condition transitioned from one status
                        to another.
                      format: date-time
                      nullable: true
                    lastUpdateTime:
                      type: string
                      description: The last time this condition was updated.
                      format: date-time
                      nullable: true
                    message:
                      type: string
                      description: A human readable message indicating details about
                        the transition.
                    reason:
                      type: string
                      description: The reason for the condition's last transition.
                      enum:
                      - HealthChecksPassed
                      - HealthChecksFailed
                      - Pending
                    status:
                      type: string
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                    type:
                      type: string
                      description: type of condition.
                      enum:
                      - PlatformHealthy
                      - WorkloadsHealthy
                  required:
                  - status
                  - type
    served: true
    storage: true
    subresources:
      status: {}


