apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Main namespace
namespace: gdc-cluster-health

resources:
- openai-web-service.yaml

images:
- name: gcr.io/cloud-alchemists-sandbox/kamek/cluster-health-validator
  newTag: 1.1.0